const songs = [
  {"title": "Shining Lights", "artist": "The Wanderers", "album": "Midnight Drive", "length": "3:45", "image": "assets/img/song.png"},
  {"title": "Echoes of Time", "artist": "Luna Sky", "album": "Celestial Dreams", "length": "4:12", "image": "assets/img/song.png"},
  {"title": "Broken Wings", "artist": "Silver Storm", "album": "Flightless", "length": "5:01", "image": "assets/img/song.png"},
  {"title": "City Nights", "artist": "Neon Pulse", "album": "Electric Heart", "length": "3:30", "image": "assets/img/song.png"},
  {"title": "Golden Horizon", "artist": "Aurora Waves", "album": "Sunrise Journey", "length": "4:05", "image": "assets/img/song.png"},
  {"title": "Midnight Whisper", "artist": "Velvet Echo", "album": "Silent Shadows", "length": "3:50", "image": "assets/img/song.png"},
  {"title": "Falling Stars", "artist": "Starlight Express", "album": "Cosmic Ride", "length": "4:20", "image": "assets/img/song.png"},
  {"title": "Lost in the Moment", "artist": "Echo Point", "album": "Frozen Time", "length": "3:58", "image": "assets/img/song.png"},
  {"title": "Rise Again", "artist": "Phoenix Flame", "album": "Ashes to Life", "length": "4:30", "image": "assets/img/song.png"},
  {"title": "Summer Rain", "artist": "The Daydreamers", "album": "Waves of Sound", "length": "3:25", "image": "assets/img/song.png"},
  {"title": "Silent Roads", "artist": "Midnight Train", "album": "Long Journey", "length": "4:45", "image": "assets/img/song.png"},
  {"title": "Neon Dreams", "artist": "City Lights", "album": "Electric Pulse", "length": "3:40", "image": "assets/img/song.png"},
  {"title": "Ocean Blue", "artist": "Deep Tide", "album": "Underwater Tales", "length": "4:10", "image": "assets/img/song.png"},
  {"title": "Golden Skies", "artist": "Sunset Riders", "album": "Endless Summer", "length": "3:55", "image": "assets/img/song.png"},
  {"title": "Fire Within", "artist": "Blaze", "album": "Inner Flame", "length": "4:35", "image": "assets/img/song.png"},
  {"title": "Crystal Clear", "artist": "Pure Sounds", "album": "Reflections", "length": "3:20", "image": "assets/img/song.png"},
  {"title": "Whispering Winds", "artist": "Nature Calls", "album": "Earth Songs", "length": "4:00", "image": "assets/img/song.png"},
  {"title": "Dreamcatcher", "artist": "Night Vision", "album": "Sleepless Nights", "length": "3:42", "image": "assets/img/song.png"},
  {"title": "Running Free", "artist": "Wild Hearts", "album": "Untamed", "length": "4:25", "image": "assets/img/song.png"},
  {"title": "Electric Love", "artist": "Voltage", "album": "Shockwave", "length": "3:48", "image": "assets/img/song.png"},
  {"title": "Frozen Tears", "artist": "Icefall", "album": "Winter's Embrace", "length": "4:15", "image": "assets/img/song.png"},
  {"title": "Lost Highway", "artist": "Dust Roads", "album": "Wanderlust", "length": "3:53", "image": "assets/img/song.png"},
  {"title": "Velvet Night", "artist": "Smooth Groove", "album": "Midnight Lounge", "length": "4:40", "image": "assets/img/song.png"},
  {"title": "Starry Eyes", "artist": "Moonlit", "album": "Lunar Love", "length": "3:38", "image": "assets/img/song.png"},
  {"title": "Gravity", "artist": "Orbit", "album": "Spacebound", "length": "4:18", "image": "assets/img/song.png"},
  {"title": "Open Road", "artist": "The Nomads", "album": "Journey On", "length": "3:29", "image": "assets/img/song.png"},
  {"title": "Heartbeat", "artist": "Pulse", "album": "Life Beat", "length": "4:02", "image": "assets/img/song.png"},
  {"title": "Silver Lining", "artist": "Cloudbreak", "album": "After the Storm", "length": "3:36", "image": "assets/img/song.png"},
  {"title": "Magic Hour", "artist": "Sunset Glow", "album": "Twilight", "length": "4:22", "image": "assets/img/song.png"},
  {"title": "Blue Horizon", "artist": "Skyline", "album": "Distant Views", "length": "3:47", "image": "assets/img/song.png"},
  {"title": "Crimson Tide", "artist": "Red Wave", "album": "Blood Moon", "length": "4:13", "image": "assets/img/song.png"},
  {"title": "Echo Chamber", "artist": "Reverb", "album": "Soundscapes", "length": "3:35", "image": "assets/img/song.png"},
  {"title": "Midnight Sun", "artist": "Polar Lights", "album": "Frozen Days", "length": "4:27", "image": "assets/img/song.png"},
  {"title": "Golden Path", "artist": "Trailblazers", "album": "Road to Nowhere", "length": "3:41", "image": "assets/img/song.png"},
  {"title": "Silent Echoes", "artist": "Ghost Notes", "album": "Haunted", "length": "4:07", "image": "assets/img/song.png"},
  {"title": "Skybound", "artist": "Aero", "album": "Flight", "length": "3:49", "image": "assets/img/song.png"},
  {"title": "Neon Rain", "artist": "Cityscape", "album": "Urban Nights", "length": "4:16", "image": "assets/img/song.png"},
  {"title": "Rising Tide", "artist": "Sea Change", "album": "Waves", "length": "3:33", "image": "assets/img/song.png"},
  {"title": "Open Skies", "artist": "Freefall", "album": "Limitless", "length": "4:04", "image": "assets/img/song.png"},
  {"title": "Electric Dreams", "artist": "Synthwave", "album": "Neon Nights", "length": "3:37", "image": "assets/img/song.png"},
  {"title": "Fading Light", "artist": "Dusk", "album": "Evening Glow", "length": "4:21", "image": "assets/img/song.png"},
  {"title": "Shadow Dance", "artist": "Nightfall", "album": "Dark Moves", "length": "3:50", "image": "assets/img/song.png"},
  {"title": "Crystal Dreams", "artist": "Mirage", "album": "Illusions", "length": "4:11", "image": "assets/img/song.png"},
  {"title": "Open Hearts", "artist": "The Believers", "album": "Faith", "length": "3:46", "image": "assets/img/song.png"},
  {"title": "Silver Moon", "artist": "Lunar Light", "album": "Night Sky", "length": "4:09", "image": "assets/img/song.png"},
  {"title": "Fireside", "artist": "Warmth", "album": "Cozy Nights", "length": "3:52", "image": "assets/img/song.png"},
  {"title": "Echoes in the Dark", "artist": "Shadowplay", "album": "Midnight", "length": "4:24", "image": "assets/img/song.png"},
  {"title": "Rivers Flow", "artist": "Current", "album": "Water Ways", "length": "3:39", "image": "assets/img/song.png"},
  {"title": "Lost Horizons", "artist": "Beyond", "album": "Far Away", "length": "4:06", "image": "assets/img/song.png"},
  {"title": "Twilight Zone", "artist": "Mystic", "album": "Between Worlds", "length": "3:43", "image": "assets/img/song.png"},
  {"title": "Electric Sky", "artist": "Volt", "album": "Charged", "length": "4:14", "image": "assets/img/song.png"},
  {"title": "Silent Waters", "artist": "Stillness", "album": "Calm", "length": "3:51", "image": "assets/img/song.png"},
  {"title": "Midnight Ride", "artist": "Dark Riders", "album": "Night Shift", "length": "4:19", "image": "assets/img/song.png"},
  {"title": "Golden Glow", "artist": "Sunbeam", "album": "Radiance", "length": "3:34", "image": "assets/img/song.png"},
  {"title": "Falling Leaves", "artist": "Autumn Breeze", "album": "Seasons", "length": "4:08", "image": "assets/img/song.png"},
  {"title": "Neon Lights", "artist": "Urban Glow", "album": "City Beat", "length": "3:44", "image": "assets/img/song.png"},
  {"title": "Silver Shadows", "artist": "Moonwalkers", "album": "Nightfall", "length": "4:23", "image": "assets/img/song.png"},
  {"title": "Lost and Found", "artist": "The Seekers", "album": "Journey's End", "length": "3:55", "image": "assets/img/song.png"},
  {"title": "Crystal Skies", "artist": "Skyline", "album": "Above", "length": "4:03", "image": "assets/img/song.png"},
  {"title": "Rising Sun", "artist": "Dawn Patrol", "album": "Morning Light", "length": "3:32", "image": "assets/img/song.png"},
  {"title": "Ocean Breeze", "artist": "Coastline", "album": "Seaside", "length": "4:20", "image": "assets/img/song.png"},
  {"title": "Echoes of You", "artist": "Resonance", "album": "Reflections", "length": "3:45", "image": "assets/img/song.png"},
  {"title": "Silver Storm", "artist": "Thunderclap", "album": "Electric Sky", "length": "4:12", "image": "assets/img/song.png"},
  {"title": "Frozen Dreams", "artist": "Icebreaker", "album": "Winter Tales", "length": "3:59", "image": "assets/img/song.png"},
  {"title": "Neon Shadows", "artist": "Glow", "album": "Electric Nights", "length": "4:26", "image": "assets/img/song.png"},
  {"title": "Midnight Bloom", "artist": "Night Garden", "album": "Dark Flowers", "length": "3:47", "image": "assets/img/song.png"},
  {"title": "Golden Sands", "artist": "Desert Rose", "album": "Endless Dunes", "length": "4:10", "image": "assets/img/song.png"},
  {"title": "Silent Storm", "artist": "Calm Before", "album": "Quiet Chaos", "length": "3:53", "image": "assets/img/song.png"},
  {"title": "Starbound", "artist": "Cosmos", "album": "Galaxy", "length": "4:15", "image": "assets/img/song.png"},
  {"title": "Electric Heartbeat", "artist": "Pulsewave", "album": "Live Wire", "length": "3:36", "image": "assets/img/song.png"},
  {"title": "Fading Echoes", "artist": "The Remnants", "album": "Afterglow", "length": "4:01", "image": "assets/img/song.png"},
  {"title": "Lost in Time", "artist": "Chronos", "album": "Timeless", "length": "3:49", "image": "assets/img/song.png"},
  {"title": "Velvet Sky", "artist": "Soft Clouds", "album": "Dreamscape", "length": "4:22", "image": "assets/img/song.png"},
  {"title": "Rising Flames", "artist": "Inferno", "album": "Burning Bright", "length": "3:41", "image": "assets/img/song.png"},
  {"title": "Ocean Eyes", "artist": "Seashell", "album": "Deep Blue", "length": "4:07", "image": "assets/img/song.png"},
  {"title": "Golden Threads", "artist": "Weavers", "album": "Tapestry", "length": "3:35", "image": "assets/img/song.png"},
  {"title": "Midnight Echo", "artist": "Shadowlight", "album": "Nocturne", "length": "4:18", "image": "assets/img/song.png"},
  {"title": "Neon Wave", "artist": "Electric Tide", "album": "Surf", "length": "3:38", "image": "assets/img/song.png"},
  {"title": "Silent Nightfall", "artist": "Darkness Falls", "album": "Twilight Zone", "length": "4:13", "image": "assets/img/song.png"},
  {"title": "Crystal River", "artist": "Blue Stream", "album": "Flow", "length": "3:54", "image": "assets/img/song.png"},
  {"title": "Fires of Dawn", "artist": "Sunrise", "album": "New Beginnings", "length": "4:05", "image": "assets/img/song.png"},
  {"title": "Echoes of Silence", "artist": "Quiet Storm", "album": "Stillness", "length": "3:46", "image": "assets/img/song.png"},
  {"title": "Silver Horizons", "artist": "Skywalkers", "album": "Beyond the Clouds", "length": "4:20", "image": "assets/img/song.png"},
  {"title": "Lost Stars", "artist": "Galaxy Riders", "album": "Stellar", "length": "3:43", "image": "assets/img/song.png"},
  {"title": "Midnight Shadows", "artist": "Night Owls", "album": "Dark Hours", "length": "4:11", "image": "assets/img/song.png"},
  {"title": "Golden Moments", "artist": "The Timeless", "album": "Forever", "length": "3:50", "image": "assets/img/song.png"},
  {"title": "Ocean's Whisper", "artist": "Tidecallers", "album": "Seascape", "length": "4:25", "image": "assets/img/song.png"},
  {"title": "Neon Heart", "artist": "City Pulse", "album": "Electric Love", "length": "3:37", "image": "assets/img/song.png"},
  {"title": "Silent Glow", "artist": "Luminescence", "album": "Light Within", "length": "4:08", "image": "assets/img/song.png"},
  {"title": "Rising Stars", "artist": "Skyfire", "album": "Ignite", "length": "3:39", "image": "assets/img/song.png"},
  {"title": "Fading Memories", "artist": "The Lost", "album": "Remember", "length": "4:03", "image": "assets/img/song.png"},
  {"title": "Velvet Dawn", "artist": "Soft Morning", "album": "New Day", "length": "3:48", "image": "assets/img/song.png"},
  {"title": "Electric Pulse", "artist": "Voltage", "album": "Current", "length": "4:17", "image": "assets/img/song.png"},
  {"title": "Crystal Light", "artist": "Clarity", "album": "Reflections", "length": "3:35", "image": "assets/img/song.png"},
  {"title": "Midnight Fire", "artist": "Dark Flame", "album": "Embers", "length": "4:21", "image": "assets/img/song.png"},
  {"title": "Golden Rays", "artist": "Sunbeam", "album": "Light Up", "length": "3:44", "image": "assets/img/song.png"},
  {"title": "Ocean Breeze", "artist": "Seafarers", "album": "Blue Horizons", "length": "4:12", "image": "assets/img/song.png"},
  {"title": "Silent Echo", "artist": "Whispers", "album": "Shadows", "length": "3:51", "image": "assets/img/song.png"},
  {"title": "Neon Dreams", "artist": "City Lights", "album": "Electric Pulse", "length": "4:19", "image": "assets/img/song.png"},
  {"title": "Falling Stars", "artist": "Starfall", "album": "Night Sky", "length": "3:37", "image": "assets/img/song.png"},
  {"title": "Lost in You", "artist": "The Wanderers", "album": "Heartstrings", "length": "4:06", "image": "assets/img/song.png"},
]
